import Head from "next/head";
import { Navbar } from "../Navigasi/Navbar";
import layout from "../../styles/layout.module.css";
import { useRouter } from "next/router"
import Alert from "../Alert";

const Layout = ({ children }) => {
  const router = useRouter(); 
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <Navbar />
      <Alert />
      <div className={
        router.asPath === "/login" || router.asPath === "/register"
          ? null
          : layout.children
        }
      >
        {children}
      </div>
    </div>
  );
};

export default Layout;
