import Head from "next/head";
import { Navbar } from "../Navigasi/Navbar";
import layout from "../../styles/layout.module.css"
import BottomNav from "../Navigasi/BottomNav";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <BottomNav/>
      <div className={layout.children}>{children}</div>
    </div>
  );
};

export default Layout;
