import dynamic from "next/dynamic";
import Head from "next/head";
import layout from "../../styles/layout.module.css";
import { useRouter } from "next/router";
import Alert from "../Alert";

const Navbar = dynamic(() => import("../Navigasi/Navbar"));

const Layout = ({ children }) => {
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="manifest" href="/manifest.json" />
            </Head>
            {typeof window !== "undefined" && <Navbar />}

            <Alert />
            <div
                className={
                    router.asPath === "/login" ||
                    router.asPath === "/register" ||
                    router.asPath.includes("/store")
                        ? null
                        : layout.children
                }
            >
                {children}
            </div>
        </>
    );
};

export default Layout;
