import Head from "next/head";
import { Navbar } from "../components/Navbar";
import Container from "@material-ui/core/Container"

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Container style={{ marginTop: "120px"}}>{children}</Container>
    </div>
  );
};

export default Layout;
