
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED = "LOGOUT_FAILED"

export const GET_USER_DATA = "GET_USER_DATA"
export const UPDATE_USER_DATA = "UPDATE_USER_DATA"

export const SET_LOCATION = "SET_LOCATION"
export const SET_PRIMARY_LOCATION = "PRIMARY_LOCATION"
export const APPEND_LOCATION = "APPEND_LOCATION"
export const DELETE_LOCATION = "DELETE_LOCATION"
export const UPDATE_LOCATION = "UPDATE_LOCATION"

export const FETCH_USER = "FETCH_USER_DATA"
export const USER_IS_UNAUTHORIZED = "USER_IS_UNAUTHORIZED"
export const SET_TOKEN = "SET_TOKEN"